name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up environment variables
        run: |
          echo "export API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "export OTHER_SECRET=${{ secrets.OTHER_SECRET }}" >> $GITHUB_ENV

      - name: Build the project
        run: |
          node your-script.js
          # В вашем коде API_KEY будет доступен через process.env.API_KEY
