jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          echo "API_KEY=$API_KEY" > .env
          node your-script.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
